### ISSUE TITLE
Widget showing wrong speed

### ISSUE THREAD

**Issue by saudiqbal** [LeeVD/plasma-applet-net-bandwidth-monitor_qt6#6]
I am seeing wrong speed if I run a local speed test.

Actual speed test 925 Mbps
Widget shows 2.0 Gb/s

It should be 1.0 Gb/s

**Comment by LeeVD** [comment]
Thanks saudiqbal.  I've also noticed this issue.  Will be fixed in the next release.

**Comment by LeeVD** [comment]
fixed in 6.2025.4.20

Please test and confirm.

**Comment by saudiqbal** [comment]
For some reason I am still seeing 2.0 Gb/s instead of 1Gb for 926 Mbps speed.

**Comment by saudiqbal** [comment]
Ran a google speed test, 110Mbps shows 240Mbps

**Comment by LeeVD** [comment]
is it definately v6.2025.4.20 in the settings page - about section?

![Image](https://github.com/user-attachments/assets/fc78d424-9163-4fb4-a34c-bc45c610c845)

I've found installing as an updates can be hit or miss.

**Comment by LeeVD** [comment]
Showing correctly for me on the latest version:

![Image](https://github.com/user-attachments/assets/426600c3-6ffd-4af6-8246-9aba539becee)

![Image](https://github.com/user-attachments/assets/8684b187-16fa-4d0f-a6a0-b99e65d538dd)

**Comment by saudiqbal** [comment]
I removed the old version and re-installed v6.2025.4.20 and it was showing the wrong speed. I rebooted the computer and now it shows the correct speed.

Looks like a complete reboot of Computer is needed to see the correct speed. Just upgrading the widget is not enough.

All good now. Thanks for the good work plus donation.

**Comment by LeeVD** [comment]
I made a number of changes to the back end logic to correct the issue, probably needed a completely memory refresh to apply the new code. 
Glad its working for you.
Cheers Saudiqbal for the generous donation, much appreciated. You're a diamond 👍
